### ISSUE TITLE
サーバを置く場所を決める

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#1]
## 概要

- サーバを置く場所をどうするか決める
 - AWS？GCP？

**Comment by t-kashima** [comment]
今回テンションが高いうちに作りたい気もするから、慣れてる方がいいかな！と思うけど。本田先生がテンション上がる方でいいのでは？

**Comment by Takashi-kun** [comment]
基本的にはベンダー固有のサービス(RDSとかそういうの)は使いたくないんで, どっちでもいい気もする
Google ならみんなのアカウントとひも付けできるから幸せな気もする
(GCP はほとんど触ったことないけど)

**Comment by Takashi-kun** [comment]
AWS 確定
https://mokmoku.slack.com/archives/develop/p1471272104000065
