### ISSUE TITLE
鍵/パスワードの管理

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#2]
## 概要

- ユーザー(SSH, その他ツール)
- AWS? とか

**Comment by t-kashima** [comment]
@Takashi-kun これSSHの公開鍵を @Takashi-kun  に渡してとりあえず開発者全員を登録してもらって、管理しておいてもらえればいいかな？というのはどうでしょう？

**Comment by segasho** [comment]
いいと思う。
@Takashi-kun 
おねしゃす
https://github.com/segasho.keys

**Comment by Takashi-kun** [comment]
あー, これは秘密鍵とか AWS(GCP)の API Key のことっすねー

公開鍵は @segasho みたいに貼っといてもらえれば
SSH ForwardAgent 使うので, 公開鍵だけ貰えればあとはよしなにログインできるようにするでござる
公開鍵は Chef に突っ込む予定です
参考: http://blog.code-life.net/blog/2014/09/07/ssh-agent-forwarding/

**Comment by t-kashima** [comment]
@Takashi-kun :bow: https://github.com/t-kashima.keys

**Comment by Takashi-kun** [comment]
@segasho 3つあるけど
@t-kashima 2つあるけど

2人とも全部使うってことすかね

**Comment by segasho** [comment]
一番下ので、おねしゃす

**Comment by Takashi-kun** [comment]
せがわ: Rx のやつ
かしま:

**Comment by t-kashima** [comment]
@Takashi-kun 下のやつで！

**Comment by Takashi-kun** [comment]
方針決まった

公開鍵 は https://github.com/mokmoku/loveit-general/issues/2#issuecomment-239854552
AWS Keyとかは Google Docs と Chef に突っ込む
Chef の鍵はDocsに入れとく
