### ISSUE TITLE
設定ファイルの管理方法

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#3]
## 概要

- dev/production での差分をどうやって管理しようかな
- 多分 Provisioning で Chef(Docker) 使うことになりそうだけど, そのリポジトリをグローバルで作っていいのか

**Comment by t-kashima** [comment]
@Takashi-kun @segasho 相談して決めて！

**Comment by segasho** [comment]
@Takashi-kun 

> dev/production での差分をどうやって管理しようかな

サーバサイド側のソースコード上で、core/config/dev or core/config/production dirを作ってビルド時に読み込みファイルを変える的な。。？的外れ？

> 多分 Provisioning で Chef(Docker) 使うことになりそうだけど, そのリポジトリをグローバルで作っていいのか

グローバルには作りたくはないが、現時点で金をかけられる余裕はない。
gitlab or localにおいておくか。。
妙案あれば。。。ほしい。

**Comment by Takashi-kun** [comment]
@segasho 
>サーバサイド側のソースコード上で、core/config/dev or core/config/production dirを作ってビルド時に読み込みファイルを変える的な。。？的外れ？

これはインフラ的な設定ファイル(nginx.conf とか)をどうやって管理するかってことですねー
結局Chefのレシピも設定ファイルもGit管理したいわけですが, GitHub に置けないとなると S3 とかになるわけだが, PR で開発できないから結局触れるのが1人だけになりそうという問題
まあ, PR は diff を貼ってもらえれば良いわけだが

#### GitHub に置かない場合の案

1. `Chef兼Infra用GitRemoteサーバ` 作ってそこに push するスタイル
    * `Chef兼Infra用GitRemoteサーバ` がすべてのInfra用ファイルの master になる
    * これが飛んだら頑張って復旧する
1. S3 に突っ込む
    * 変更するたびにお金がかかるよ！
1. GitLab 建てる
    * まあ後々はってかんじすかねー

**Comment by t-kashima** [comment]
3.はないかなー、後々でもできれば外でプライベートリポジトリのあるサービスに載せたい

**Comment by segasho** [comment]
>これはインフラ的な設定ファイル(nginx.conf とか)をどうやって管理するかってことですねー

任したい！希望は楽な方法！

> 結局Chefのレシピも設定ファイルもGit管理したいわけですが, GitHub に置けないとなると S3 とかになるわけだが, PR で開発できないから結局触れるのが1人だけになりそうという問題

てっきりChefとかは、 @Takashi-kun に完全に任すつもりだったので、問題ないかと思ってたが、いかがだろう。

**Comment by Takashi-kun** [comment]
1パターンでいくかなー

**Comment by Takashi-kun** [comment]
1パターンにした
```
Chef兼Infra用GitRemoteサーバ 作ってそこに push するスタイル
Chef兼Infra用GitRemoteサーバ がすべてのInfra用ファイルの master になる
これが飛んだら頑張って復旧する
```

**Comment by Takashi-kun** [comment]
↑を何処かにいい感じの図で描いとく

**Comment by Takashi-kun** [comment]
図書いて Wiki にリンク貼っといた
