### ISSUE TITLE
SSL証明書

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#5]
## 概要

- アプリ(iOS, Android) なら HTTPS 必須じゃなかったっけ

**Comment by t-kashima** [comment]
@Takashi-kun 必須ですね！SSLにしたいので、Amazonの無料の証明書のやつ使えないかな？
http://dev.classmethod.jp/cloud/aws/acm-available-in-tokyo/

**Comment by Takashi-kun** [comment]
@t-kashima 
そうなんすねーやっぱり
これだと ELB で SSL 解くことになって, Cipher Suit の対応に柔軟にできなそうな気もする
http://tkengo.github.io/blog/2015/12/01/https-details/
https://developer.android.com/reference/javax/net/ssl/SSLEngine.html

無料証明書試してみてからですかねー

**Comment by Takashi-kun** [comment]
このパターンで( https://mokmoku.slack.com/archives/develop/p1471277273000199 )
```
* ワイルドカードの場合 or API 毎に FQDN なし(Header, path に API 情報)
iOS -[https]-> ELB(HTTPS紐解き) -[http]-> nginx -> (proxy) -> 内部ELB1 -> nginx -> api1(Golang)
                                                              内部ELB2 -> nginx -> api2(Golang)
```

**Comment by Takashi-kun** [comment]
↑を何処かにいい感じの図で書いとく

**Comment by Takashi-kun** [comment]
図に描いてリンク貼っといた
