### ISSUE TITLE
アカウント管理

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#6]
## 概要

- 支払い含む

**Comment by t-kashima** [comment]
@Takashi-kun  アカウントのID/PASSはDocs管理でいいかなと思ってます！支払いはどんなものが入ってくることが想定されるかな？(特に緊急度が高いもの)

**Comment by Takashi-kun** [comment]
@t-kashima 
>支払いはどんなものが入ってくる

サーバ費用が諸々来ると思うんだけど, それを CSV とかで取得して Google Drive に突っ込む感じですかねー
コスト周りをちゃんと管理しないと後々面倒なので, あらかじめルール決めておきたいでござる

**Comment by t-kashima** [comment]
@Takashi-kun 費用はエクセルで管理しますかねー！お金まわりは一旦お金あつめてそこから払うとかの方がいいかもしれない。みんなで話しましょう。

**Comment by Takashi-kun** [comment]
これGoogle Docでいいよね
