### ISSUE TITLE
ソース(レシピ的なもの含む)管理場所

### ISSUE THREAD

**Issue by t-kashima** [mokmoku/loveit-general#8]
## 概要

- GitHub のパブリックはなー
- GitLab 建てるのもなー

**Comment by t-kashima** [comment]
@Takashi-kun ソースはリリースまではパブリックでいいかなと思ったり。でもソースにキーてきなものが入ったりすると思うのでその辺が切り分け難しそうだったら、プライベートリポジトリかな？

**Comment by Takashi-kun** [comment]
今回はDB周りもすべて内部DNS引くように作るから, `loveit-server` はパブリックでもいい気がするんだけど, 完璧に固めるならVPNとかでSecurityGroupをガチガチにしたい

下にも書いたけど, Infra用リポジトリはGitHub使わないので, そこにアプリケーションが使う設定フィアルも管理させて ENV とかで読み込ませて, `loveit-server` は環境変数からパスワードとか取るようにすればいいかも(Golang で環境変数渡して起動できるのかは知らん)
https://github.com/mokmoku/loveit-general/issues/3#issuecomment-239817782

**Comment by t-kashima** [comment]
👀

**Comment by Takashi-kun** [comment]
これ決まってた

#### レシピ

* 下記のコメントに残した通り Wiki に図描いといた
    * https://github.com/mokmoku/loveit-general/issues/3#issuecomment-240099395

#### server

* イメージとしては下記みたいな感じでそれぞれ `app-user` 以下のディレクトリを Docker でマウントさせる
```
app-user/repos/loveit-server <== GitHub 管理下
app-user/conf/connection.json <== deploy サーバから rsync
```
環境変数でファイルのパス渡す
※ 環境変数はとれますね( https://hydrocul.github.io/wiki/programming_languages_diff/vars/env.html )
